CREATE TABLE users (
	id SERIAL PRIMARY KEY,
	name TEXT NOT NULL,
	password TEXT NOT NULL,
	email TEXT NOT NULL UNIQUE,
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE urls (
	id SERIAL NOT NULL PRIMARY KEY,
	user_id INTEGER NOT NULL,
	url TEXT NOT NULL,
	short_url TEXT NOT NULL,
	url_visit_count INTEGER NOT NULL,
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE sessions (
	id SERIAL NOT NULL PRIMARY KEY,
	user_id INTEGER NOT NULL UNIQUE,
	token TEXT NOT NULL,
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);

ALTER TABLE
	"urls"
ADD
	CONSTRAINT "urls_fk0" FOREIGN KEY ("user_id") REFERENCES "users"("id");

ALTER TABLE
	"sessions"
ADD
	CONSTRAINT "sessions_fk0" FOREIGN KEY ("user_id") REFERENCES "users"("id");